### PR TITLE
Features/heka stdliblogging

### PR DESCRIPTION
**Pull request by crankycoder**
- I've moved the python standard logging output sender into the heka.streams namespace. 
- The heka.senders namespace has finally been removed closing issue #4 
- Updated the documentation to include example configuration for each stream type
- Added working examples using the INI configuration to the examples directory
- bumped revision to 0.30.2 (issue #9 required for marketplace)

The most significant change here is with how output to the stdlib logging module works.

The heka.streams.StdLibLogging stream _requires_ the use of heka.encoders.StdlibJSONEncoder.  In a nutshell, there is an mismatch between the streams API and what the python logging intefarce needs.

With the split in the heka client API between streams and encoding - the output stream only sees a write(msg) call.  Python's logging interace requires a log level (int) and a string.

The StdlibJSONEncoder is identical to the JSONEncoder, except that is prepends a single byte to encode the log level.  This changes the behavior of the output as we used to simply write out the payload to the python logger.

Changing the behavior from the previous version is not ideal, but I can't see why someone is using heka to write to the python logging as an output stream except for debugging purposes.

### CODE REVIEW

**Comment by trink** [comment]
FYI: the encoding has been removed from the message.proto header since a message.proto JSON encoding is pretty useless. TCP/UDP inputs have been updated and can take any type of data stream (just uses different ports for each type)
https://github.com/mozilla-services/heka/issues/381

**Comment by crankycoder** [comment]
Cool,  let me take a look at pull request 401 tonight.  Do we have a plan
already for an alternative encoding other than protobuf to support node.js
clients?

**Comment by trink** [comment]
Yeah, the redesign is definitely in the right direction.  Inclusion of alternate encodings/support of more data formats is the goal.  The StreamParsers are shared between inputs so now we have better parity between Logfile, TCP, and UDP inputs.  If you have specific node.js data formats/use cases create an issue to make sure we account for them and that the system is easily extensible. thanks!

**Comment by crankycoder** [comment]
@rafrombrc, @trink : This PR should be ok to review now. It's targetted for heka 0.3.0 compatibility - so the header for message encoding is still there.

I've split off the changes for the removal of the message encoding header into the features/heka-0.4.0 branch.

**Pull request merged**
